spring:
  application:
    name: ms-product

  h2:
    console:
      enabled: true

server:
  port: 7878
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka

